### ISSUE TITLE
AGO button menu

### ISSUE THREAD

**Issue by Shole123** [AntiGameOrigin/AntiGameOrigin-Whole-SourceCode#23]
Started developing:
![img](http://s18.postimg.org/p0owr4ao9/test.png)

Will add link for reporting bugs, link for suggestions, much more.
Still thinking.

I have just tested this, it is not planned for 6.0.1 maybe later for 6.0.2.
For now important is message page, and all what we planned for 6.0.1.

**Comment by Rivenscryr** [comment]
Hmm I wouldn't like this as a user
It has no important feature and fills the browser

**Comment by Shole123** [comment]
Suggestion rejected.
