### ISSUE TITLE
Loca for abbreviations

### ISSUE THREAD

**Issue by Rivenscryr** [AntiGameOrigin/AntiGameOrigin-Whole-SourceCode#24]
```javascript
parseIntRess: function (a) {
        a = STR.trim(a.match(/: ([^<]+)*/)[1]);
        if (a.match(/^[0-9]{1,3}\.[0-9]{3}$/))
            a = a.replace('.', '');
        else if(a.match(/^([0-9]{1,3}(\.|,))?[0-9]{1,3}(Md|Bn|Mrd)/))
            a = a.replace(/,/g,'.').replace(/Md|Bn|Mrd/g,'')*1000000000;
        else if(a.match(/^([0-9]{1,3}(\.|,))?[0-9]{1,3}(M|m)/))
            a = a.replace(/,/g,'.').replace(/(M|m)/g,'')*1000000;
        return a = Math.round(a);
    }
```

We need localization for those abbreviations (Md, Mrd, Bn)
can you ask for those?

**Comment by Shole123** [comment]
Skynet asked same thing on origin 
http://board.origin.ogame.gameforge.com/board15-ideas-planet/board28-suggestions/p39588-add-localization-details-for-tool-developers/#post39588

**Comment by Rivenscryr** [comment]
Yes but we can't wait for gameforge to implement this, that would take ages at best

**Comment by Rivenscryr** [comment]
Because we can't release 6.0.1 without those abbreviations

**Comment by Shole123** [comment]
Just put standard prefix, as Vulca did.
"internationnal metric prefixes"

**Comment by Rivenscryr** [comment]
No I need those abbreviations to READ the resources

**Comment by Shole123** [comment]
What is wrong with this way now?

**Comment by Rivenscryr** [comment]
It only supports 3 languages, not all

**Comment by Shole123** [comment]
Metric system:
k,M,Bn is used in every community

Confirmed by developer.

**Comment by Rivenscryr** [comment]
![](https://img5.picload.org/image/wadrpld/spio.jpg)

http://board.origin.ogame.gameforge.com/board6-origin/board5-feedback-discussions/8077-every-community-needed-compilation-of-all-abbreviations-for-million-billion/

**Comment by Rivenscryr** [comment]
I have another idea to solve this issue
But I need your help to test some values

**Comment by Shole123** [comment]
Developer said it should be everywhere same, i have our talk documented. Maybe he didnt understod what i meant. 

About board post, i will put it in news section when i come home. 

About another idea, i am home in 2-3 hours so we will talk than.

**Comment by Rivenscryr** [comment]
Yeah that idea will only solve loot issue
But I would like to read Metal, Crystal and Deut values as well

**Comment by Shole123** [comment]
I am available on IRC, from now on. :)

**Comment by Shole123** [comment]
Loca done.

http://board.origin.ogame.gameforge.com/board3-news/board12-user-projects/p41596-abbreviations-for-million-billion/#post41596
