### ISSUE TITLE
Collect / fleetsave routine: planet switching

### ISSUE THREAD

**Issue by Rivenscryr** [AntiGameOrigin/AntiGameOrigin-Whole-SourceCode#26]
Currently the automatic planet switching is bound to setting 
"E14": "Select fleet page 1 with the return-key"

Since this option is redundant now I'd suggest changing it to "Activate auto planet switch on collect / FS routines" or something similar

**Comment by Shole123** [comment]
Yes, but i don't think that it will be done until 6.0.1.
It needs Loca support for all languages. 

Also check my comment on last commit, especially that part with fleet3.js line368
I don't know how it was before, but maybe it should go directly from fleet3 to next planet and not fleet3->fleet1->Next planet

What do you think?

**Comment by Rivenscryr** [comment]
Before it was fleet3 -> movement -> user hits return key -> next planet
Switching planet directly after sending ships is not possible

**Comment by Shole123** [comment]
Yep, GF changed it to fleet3 -> fleet1 
Than everything is fine :)

**Comment by Rivenscryr** [comment]
How does it work with localization? We need some more things to be localized

**Comment by Shole123** [comment]
Function fixed.
Loca requested, this issue closed Loca issue opened.
