### ISSUE TITLE
Galaxy page, spying on click cause error

### ISSUE THREAD

**Issue by Shole123** [AntiGameOrigin/AntiGameOrigin-Whole-SourceCode#28]
Spying in galaxy with click sometimes gives you error.

![img](http://s2.postimg.org/q7ygltqgp/Screenshot.png)

**Comment by Rivenscryr** [comment]
Is that a bug of AGO or of OGame itself? Try spying without AGO

**Comment by Shole123** [comment]
Yeah, OGame itself
