### ISSUE TITLE
Support for Speedsim, DragoSim, OSimulate

### ISSUE THREAD

**Issue by Rivenscryr** [AntiGameOrigin/AntiGameOrigin-Whole-SourceCode#8]
Should we maintain support for those sims? If so, we have multiple possibilities:
* Use topraider.eu API interface to retrieve data
* Use our own API interface on a server
* Retrieve data by XHTMLRequest when you click on the button

**Comment by Shole123** [comment]
We will use new TrashSim by Warsaalk. 
It is also using API key.

**Comment by Shole123** [comment]
https://trashsim.universeview.be/

**Comment by Rivenscryr** [comment]
So only TrashSim it is then? Others we'll abandon then?

**Comment by Shole123** [comment]
Yes, only TrashSim, other to abandon.
